handle preload conversations

diff --git a/askmistral b/askmistral
--- a/askmistral
+++ b/askmistral
@@ -2,58 +2,106 @@
 
 source .env
 apikey=$API_KEY
+model=$MODEL
+timestamp=$(date +"%Y-%m-%d_%H:%M")
+load_type="prompt"
 
-init=1
-model="mistral-tiny"
-while true; do
-    if [ "$init" -eq 1 ]; then
-        init=0
-        if [ "$#" -eq 2 ]; then
-            model="$1"
-            result="$2"
-        elif [ "$#" -eq 3 ] && [ "$2" == "-f" ]; then
-            model="$1"
-            file="$3"
-            if [ -f "$file" ]; then
-                result=$(cat "$file")
-                echo "File content:"
-                echo "$result"
-                # Read the content of the file and escape special characters for JSON
-                result=$(jq -n --arg text "$result" '$text')
-            else
-                echo "Error: File not found or invalid option."
-                exit 1
-            fi
-        else
-            echo "Error: Invalid usage. Please use either './askmistal <model> \"string\"' or \
-                    './script.sh <model> -f file.txt'"
-            exit 1
-        fi
-        json_data=$(jq -n \
-            --arg model $model \
-            --argjson messages "[{\"role\":\"user\",\"content\":$result}]" \
-            '{model: $model, messages: $messages}'
-        )
+print_help() {
+  echo "Usage: $0 [-f <filepath>] [-c <conversationfile>] [-m <model>] <prompt>"
+  echo "Options:"
+  echo "  -f <filepath>            Specify a file path"
+  echo "  -c <conversationfile>    Specify a conversation file path"
+  echo "  -m <model>               Specify a model"
+  echo "  -h                       Display this help message"
+  exit 1
+}
 
-    else read -p "Enter input (-f for file, q to exit): " input
-        if [ "$input" = "q" ]; then
-            # output the conversation to a filen
-             timestamp=$(date +%s)
-             echo "$json_data" > "./conversations/$timestamp.json"
-             break
-        fi
-        if [ "$input" == "-f" ]; then
-            read -p "Enter filename: " file
-            input=$(cat "$file") 
-            echo "File content:"
-            echo "$input"
-        fi  
-        input=$(jq -n --arg text "$input" '$text')
-        json_data=$(echo "$json_data" | jq --argjson user_msg \
-                 "{ \"role\": \"user\", \"content\": $input }" \
-                 '.messages += [$user_msg]')
-    fi
+while getopts ":f:c:m:h" opt; do
+    case $opt in
+      f)
+          filepath="$OPTARG"
+          load_type="file"
+          ;;
+      c)
+          conversationfile="$OPTARG"
+          load_type="conversation"
+          ;;
+      m)
+          model="$OPTARG"
+          ;;
+      h)
+          print_help
+          ;;
+      \?)
+          echo "Invalid option: -$OPTARG" >&2
+          exit 1
+          ;;
+      :)
+          echo "Option -$OPTARG requires an argument." >&2
+          exit 1
+          ;;
+    esac
+done
+
+shift $((OPTIND - 1))
+
+if [ $load_type == "file" ]; then
+    prompt=$(cat "$filepath")
+    prompt=$(jq -n --arg text "$prompt" '$text')
+    json_data=$(jq -n \
+        --arg model $model \
+        --argjson messages "[{\"role\":\"user\",\"content\":$prompt}]" \
+        '{model: $model, messages: $messages}'
+    )
+
+elif [ $load_type == "conversation" ]; then
+    prompt=$(cat "$conversationfile")
+    json_data=$(jq '.' "$conversationfile")
+else
+    prompt="$1"
+    json_data=$(jq -n \
+        --arg model $model \
+        --argjson messages "[{\"role\":\"user\",\"content\":\"$prompt\"}]" \
+        '{model: $model, messages: $messages}'
+    )
+fi
+
+if [ $load_type != "conversation" ]; then
+    response=$(curl --location "https://api.mistral.ai/v1/chat/completions" \
+                    --header 'Content-Type: application/json' \
+                    --header 'Accept: application/json' \
+                    --header "Authorization: Bearer ${apikey}" \
+                    --data "$json_data")
+
+    echo "$response" | jq -r '.choices[0].message.content'
+    assistant_msg=$(echo "$response" | jq '.choices[0].message') 
   
+    json_data=$(echo "$json_data" | jq  --argjson assistant_msg "$assistant_msg" \
+              '.messages += [$assistant_msg]')
+    echo "$json_data" > "./conversations/$timestamp.json"
+
+else 
+    # print last message
+    last_msg=$(echo "$json_data" | jq '.messages[-1].content')
+    echo "$last_msg"
+fi
+
+while true; do
+    read -p "Enter input (-f for file, q to exit): " input
+    if [ "$input" = "q" ]; then
+        # output the conversation to a file
+         break
+    fi
+    if [ "$input" == "-f" ]; then
+        read -p "Enter filename: " file
+        input=$(cat "$file") 
+        echo "File content:"
+        echo "$input"
+    fi  
+    input=$(jq -n --arg text "$input" '$text')
+    json_data=$(echo "$json_data" | jq --argjson user_msg \
+             "{ \"role\": \"user\", \"content\": $input }" \
+             '.messages += [$user_msg]')
   
     response=$(curl --location "https://api.mistral.ai/v1/chat/completions" \
                     --header 'Content-Type: application/json' \
@@ -66,5 +114,10 @@ while true; do
   
     json_data=$(echo "$json_data" | jq  --argjson assistant_msg "$assistant_msg" \
               '.messages += [$assistant_msg]')
+    if [ -e "$conversationfile" ]; then
+        echo "$json_data" > "$conversationfile"
+    else
+         echo "$json_data" > "./conversations/$timestamp.json"
+    fi
 done
 echo "Bye!"
